name: SimpleCommands
version: 1.0
author: Hexye
main: me.NWImAle.SimpleCommands.Main
description: Plugin made to have some useful but also simple commands

commands:
   scbc:
      usage: /scbc <message>
      description: Broadcast a message.
   scheal:
      usage: /scheal
      description: Heal yourself.
   screload:
      usage: /screload
      description: Reload the Plugin.
   scinventory:
      usage: /scinventory <player>
      description: See inventory of another player.